title: tripoloski blog
author: arsalan
email: arsalan.dp@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
    Hello i am arsalan. information system student, i blog about cyber security,
    ctf writeup , web development , and more about tech. born and raised in
    indonesia , currently living in indonesia
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 20
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: https-tripoloski1337-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/tripoloski_1337
      icon: twitter-square
      color: cyan
    - url: https://github.com/tripoloski1337
      icon: github-square
      color: purple
    - url: https://id.linkedin.com/in/arsalan-diponegoro
      icon: linkedin
      color: yellow

# Build settings
# theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
#  - liquid-md5
#  - jekyll/tagging
